services:
  _defaults:
    autowire: true
    autoconfigure: true
  Kiwi\Contao\BlueprintsBundle\Controller\BlueprintPreviewController:
    public: true
  Kiwi\Contao\BlueprintsBundle\DataContainer\Article:
    public: true
  Kiwi\Contao\BlueprintsBundle\DataContainer\BlueprintArticle:
    public: true
  Kiwi\Contao\BlueprintsBundle\DataContainer\BlueprintArticleCategory:
    public: true
  Kiwi\Contao\BlueprintsBundle\DataContainer\Content:
    public: true
  Kiwi\Contao\BlueprintsBundle\Blueprint:
    public: true
  Kiwi\Contao\BlueprintsBundle\EventListener\CompileArticleListener: ~
  Kiwi\Contao\BlueprintsBundle\EventListener\GetArticlesListener: ~
  Kiwi\Contao\BlueprintsBundle\EventListener\GetFrontendModuleListener: ~